feat: support twin.macro
modern-js-dev/modern.js pull request #1232
Opened 2022-06-21 05:19 UTC by targeral

# PR Details

support twin.macro

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-21 06:24 UTC, chenjiahan commented on packages/toolkit/node-bundle-require/src/index.ts
> +    if (typeof options?.autoClear === 'undefined' || options.autoClear) {
`typeof options?.autoClear === 'undefined'` 可以直接写成 `options?.autoClear === undefined`

2022-06-21 06:53 UTC, chenjiahan commented on packages/cli/plugin-tailwind/src/cli.ts
> +          const modernConfig = require('${path.join(files[0])}').default;
这里 `.default` 不一定存在的，需要判断下（有可能是通过 `module.exports` 导出）

2022-06-21 06:54 UTC, chenjiahan commented on packages/cli/plugin-tailwind/src/cli.ts
> +            && modernConfig.tools
这段字符串代码要不单独抽取一个函数把，放在这里影响可读性

2022-06-21 07:42 UTC, targeral commented on packages/cli/plugin-tailwind/src/cli.ts
> +            && modernConfig.tools
嗯 可以，不过如果可以用babel-chain的话，也许可读性会好些

2022-06-21 08:43 UTC, yimingjfe commented on packages/cli/plugin-tailwind/src/cli.ts
> +            console.info(JSON.stringify(modernConfig));
这里是不是可以直接用 modern-js/utils 中的 createDebugger ？

2022-06-21 10:18 UTC, targeral commented on packages/cli/plugin-tailwind/src/cli.ts
> +            console.info(JSON.stringify(modernConfig));
可能不太行，这个文件生成位置不一定能拿到 modern-js/utils，不过我这里可以删除这段代码。

2022-06-22 07:27 UTC, targeral commented on packages/cli/plugin-runtime/src/cli/index.ts
> +              /**
@xuchaobei 辛苦 check一下这里。

2022-06-22 07:27 UTC, targeral commented on packages/cli/webpack/src/config/base.ts
> +        ).map(a =>
@chenjiahan 辛苦 check 一下这里

2022-06-22 07:27 UTC, targeral commented on website/docs/guides/usages/css/tailwindcss.md
> +## 使用 [`Twin`]((https://github.com/ben-rogerson/twin.macro)) 库
@chenjiahan @xuchaobei 增加的文档内容

2022-06-22 07:53 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +        ).map(a =>
没问题滴，这里之前我就想修正，不过感觉有一定影响面，没敢下手

2022-06-22 07:54 UTC, chenjiahan commented on website/docs/guides/usages/css/tailwindcss.md
> +在上一章中介绍了什么是 CSS-in-JS 以及社区常用的 CSS-in-JS 库 [styled-components](https://styled-components.com/)。这一部分将要介绍如何通过 [`Twin`](https://github.com/ben-rogerson/twin.macro) 在 CSS-in-JS 中使用 [Tailwind CSS](https://
`Css-in-JS` -> `CSS-in-JS`

2022-06-22 07:56 UTC, chenjiahan commented on website/docs/guides/usages/css/tailwindcss.md
> +## 使用 [`Twin`]((https://github.com/ben-rogerson/twin.macro)) 库
((https://github.com/ben-rogerson/twin.macro)) 多了一对括号

2022-06-22 07:57 UTC, chenjiahan commented on website/docs/guides/usages/css/tailwindcss.md
> +`twin.macro` 默认会读取项目目录下的 `tailwindcss.config.js` 文件，或者通过 `babel-plugin-macro` 上的 [`twin.config`](https://github.com/ben-rogerson/twin.macro/blob/master/docs/options.md#options) 指定的文件路径读取 Tailwind CSS
`不过在 Modern.js 不需要` -> `不过在 Modern.js 中不需要`

2022-06-22 07:59 UTC, targeral commented on website/docs/guides/usages/css/tailwindcss.md
> +在上一章中介绍了什么是 CSS-in-JS 以及社区常用的 CSS-in-JS 库 [styled-components](https://styled-components.com/)。这一部分将要介绍如何通过 [`Twin`](https://github.com/ben-rogerson/twin.macro) 在 CSS-in-JS 中使用 [Tailwind CSS](https://
OK

2022-06-22 08:07 UTC, targeral commented on packages/cli/webpack/src/config/base.ts
> +        ).map(a =>
我本地想修改 ensureAbsolutePath 这个，不过会影响其他使用到这个函数的地方。所以只是在这里做了处理。那这里先这样处理，观察一下。

2022-06-23 02:59 UTC, xuchaobei requested changes

2022-06-23 02:59 UTC, xuchaobei commented on packages/cli/plugin-runtime/src/cli/index.ts
> +               * So need to add aliase
typos: aliase -> alias

2022-06-23 03:24 UTC, chenjiahan approved these changes

2022-06-23 03:29 UTC, xuchaobei approved these changes

2022-06-23 03:29 UTC, merged