Feat/streaming ssr
modern-js-dev/modern.js pull request #1848
Opened 2022-10-11 11:10 UTC by GiveMe-A-Name

# PR Details

Feat: Support React 18 Streaming SSR

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-12 09:58 UTC, xuchaobei commented on packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
> +                  case StreamingStatus.Leave: {
Leave 什么场景使用？

2022-10-12 09:58 UTC, xuchaobei commented on packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/template.ts
>      const builedBeforeTemplate = buildBeforeEntryTemplate(beforeEntryTemplate, {
typo: builed

2022-10-12 09:58 UTC, xuchaobei commented on packages/server/prod-server/src/libs/render/cache/index.ts
> +      const renderResult = await renderFn(context);
和 56-62 行重复了，封装成一个函数？

2022-10-12 09:58 UTC, xuchaobei commented on packages/server/prod-server/src/server/modern-server.ts
> +        .pipe(
如果是使用真正的流 （onShellReady 中 pipe)，每次有新的流产生时，都会经过这个 Transform 做转换，会导致数据重复吧？

2022-10-12 10:03 UTC, xuchaobei requested changes

2022-10-12 10:03 UTC, xuchaobei commented on packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
> +enum StreamingStatus {
这几个状态可以做下注释，命名上是否能再优化下，比如 entry 改成 start ? entry 和 streaming 不是同类型的词语

2022-10-12 10:03 UTC, xuchaobei commented on packages/runtime/plugin-runtime/src/ssr/serverRender/utils.ts
> +  return (
这段逻辑的作用是什么呢？

2022-10-17 03:58 UTC, GiveMe-A-Name commented on packages/server/prod-server/src/libs/render/cache/index.ts
> +      const renderResult = await renderFn(context);
done

2022-10-17 03:59 UTC, GiveMe-A-Name commented on packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/template.ts
>      const builedBeforeTemplate = buildBeforeEntryTemplate(beforeEntryTemplate, {
done

2022-10-17 06:19 UTC, xuchaobei approved these changes

2022-10-17 09:32 UTC, merged