feat: extract the data loader
modern-js-dev/modern.js pull request #2209
Opened 2022-11-25 03:44 UTC by yimingjfe

# PR Details

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-25 03:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/modern-js-dev/modern.js?pullRequest=2209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/modern-js-dev/modern.js?pullRequest=2209) before we can accept your contribution.<br/>**9** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: caohuilin<br/>:white_check_mark: chenjiahan<br/>:white_check_mark: zllkjc<br/>:white_check_mark: xuchaobei<br/>:white_check_mark: sanyuan0704<br/>:white_check_mark: JSerFeng<br/>:white_check_mark: 9aoy<br/>:white_check_mark: targeral<br/>:white_check_mark: yimingjfe<br/>:x: fireairforce<br/>:x: Asuka109<br/>:x: clChenLiang<br/>:x: KyrieLii<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/modern-js-dev/modern.js?pullRequest=2209) it.</sub>

2022-11-28 09:50 UTC, yimingjfe commented on packages/toolkit/utils/src/test-utils.ts
> +export const initSnapshotSerializer = (root: string) => {
加下注释

2022-11-28 12:06 UTC, xuchaobei requested changes

2022-11-29 12:45 UTC, xuchaobei approved these changes

2022-11-30 09:42 UTC, merged