feat: support as a pure api service
modern-js-dev/modern.js pull request #544
Opened 2022-01-26 04:01 UTC by yimingjfe

# PR Details

Modernjs 工程项目支持纯粹的 API 服务

## Description

主要修改点：

1、当只有 api 目录时，不执行前端的一些逻辑；如 webpack 构建，前端路由注入等。
2、将 route.json 的生成逻辑，从 webpack plugin 改为放到一个函数中；不依赖 webpack。
3、修改编译完成或启动 server 后的展示逻辑，支持纯 api 服务时；告知用户服务已启动完成。

## Related Issue

https://github.com/modern-js-dev/modern.js/issues/519
https://github.com/modern-js-dev/modern.js/issues/524

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-26 04:03 UTC, leeight requested changes
这个改动最好补充 Integration Test 的测试用例

2022-01-26 04:05 UTC, leeight commented on packages/cli/plugin-analyze/src/index.ts
> +        });
其实可以改成

```
if (!existSrc) {

        const { routes } = await (mountHook() as any).modifyServerRoutes({
          routes: [],
        });

        debug(`server routes: %o`, routes);

        AppContext.set({
          ...appContext,
          existSrc,
          serverRoutes: routes,
        });
  return;
}
```

避免这么多的 diff 产生

2022-02-07 06:22 UTC, zllkjc commented on packages/solutions/app-tools/tests/commands/build.test.ts
> +      existSrc: false,
这里啥意思呀，为啥会在 appDirectory 里

2022-02-07 06:35 UTC, yimingjfe commented on packages/solutions/app-tools/tests/commands/build.test.ts
> +      existSrc: false,
这里写错了，已修改。

2022-02-07 06:55 UTC, zllkjc approved these changes

2022-02-07 08:00 UTC, yimingjfe commented
> 这个改动最好补充 Integration Test 的测试用例

已补充在 tests/integration/api-service-koa 下，非 API 服务项目由之前的集成用例可以保证。

2022-02-07 08:01 UTC, merged