feat: support disableCssExtract
modern-js-dev/modern.js pull request #822
Opened 2022-03-29 08:07 UTC by targeral

# PR Details

support output.disableCssExtract

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [x] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-30 09:12 UTC, chenjiahan commented on packages/cli/webpack/src/utils/createCSSRule.ts
> +      c.uses.delete('mini-css-extract');
这里 delete 的逻辑稍微有点不直观，是不是可以在上面 `use('mini-css-extract')` 的时候直接加条件判断，而不是 use 之后再 delete

2022-03-30 09:13 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
「只在生产环境启用」的收益是什么嘞，是不是可以考虑让 dev 和 build 保持一致

2022-03-30 09:57 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
我去调研一下其他框架哈

2022-03-30 10:19 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
看了下，应该只在生产环境启用更合适一些。属于 webpack 官方推荐用法：![image](https://user-images.githubusercontent.com/7237365/160809159-c73df63e-a0b5-4909-957a-8766e722f36e.png)

2022-03-31 02:00 UTC, chenjiahan approved these changes

2022-03-31 02:04 UTC, chenjiahan requested changes

2022-03-31 02:04 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
应该是 `!this.options.output?.disableCssExtract && isProd()`

2022-03-31 02:04 UTC, chenjiahan commented on packages/cli/webpack/src/utils/createCSSRule.ts
> +    .when(!(disableCssExtract && isProd()), c => {
应该是 `!disableCssExtract && isProd()`

2022-03-31 02:04 UTC, chenjiahan commented on packages/cli/webpack/src/utils/createCSSRule.ts
> +    .when(disableCssExtract && isProd(), c => {
应该是 `disableCssExtract || !isProd()`

2022-03-31 02:04 UTC, chenjiahan commented on packages/cli/webpack/src/utils/createCSSRule.ts
> +    .when(!(disableCssExtract && isProd()), c => {
建议提取一个变量，这样本文件里的两处代码就不用写重复的逻辑了

```js
const isExtractCSS = !disableCssExtract && isProd();
```

2022-03-31 03:04 UTC, targeral commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
不是吧，应该是 `!this.options.output?.disableCssExtract || !isProd()`

2022-03-31 03:04 UTC, targeral commented on packages/cli/webpack/src/utils/createCSSRule.ts
> +    .when(!(disableCssExtract && isProd()), c => {
OK

2022-03-31 03:23 UTC, chenjiahan commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
MiniCssExtractPlugin 不是只在生产环境下启用嘛，为啥是 `|| !isProd()`

2022-03-31 06:34 UTC, targeral commented on packages/cli/webpack/src/config/base.ts
> +    if (!(this.options.output?.disableCssExtract && isProd())) {
🙆‍♂️

2022-03-31 06:56 UTC, chenjiahan approved these changes

2022-03-31 07:12 UTC, merged